bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
#from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView


app_name ='main'
urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию? ')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях? ')

    #def delete(self, *args, **kwargs):
    #    for bb in self.bb_set.all():
    #        bb.delete()
    #    super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass

main/forms.py
from django import forms
from .models import AdvUser

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmaiField(required = True, label = 'Адреса електронної пошти')
    class Mete:
        model = AdvUser
        fields = ('username','email','first_name','last_name','send_messages')

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reserve_lazy
from django.shortcuts import get_object_or_404
from .models import AdvUser
from .forms import ChangeUserInfoForm
# Create your views here.
def index (request):
    return render(request, 'main/index.html')

def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

class BBLoginView(LoginView):
    template_name='main/login.html'

@login_required #декоратор @login_reqyired -  доступ до сторінки профілю надається тільки зареєстрованим користувачам
def profile(request):
    return render(request, 'main/profile.html')

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoForm (SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_info.html'
    form_class = ChangeUserInfoForm
    succecc_url = reverse_lazy('main:profile')
    success_message = 'Дані змінено'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def get_object (self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset= "UTF-8" >
  <meta name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title> {% block title %}Головна{% endblock %} - Дошка оголошень</title>
  {% bootstrap_css %}
  <link rel= "stylesheet" type= "text/css" href = "{% static 'main/style.css' %}">
  {% bootstrap_javascript jquery='slim' %}
</head>
<body class = "container-fluid">
  <header class = "mb-4">
    <h1 class= "display-1 text-center">Оголошення</h1>
  </header>
  <div class= "row">
    <ul class = "col nav justify-content-end border">
      <li class="nav-item"><a class="nav-link" hrеf= "#">Реєстрація</a></li>
      {% if user.is_authenticated %}
      <li class= "nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown"
        href= "#" role="button" aria-haspopup="true" aria-expanded = "false">Пpoфіль</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href= "{% url 'main:profile' %}">Moї оголошення</a>
            <a class="dropdown-item" hrеf= "#">Змінити особисті дані</a>
            <a class="dropdown-item" hrеf= "#" >Змінити пароль</a>
            <div class=" dropdown-divider"></div>
            <a class="dropdown-item" hrеf= "{% url 'main:logout' %}" >Вийти</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" hrеf= "#" >Видалити</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item"><a class= "nav-link" href= "{% url 'main:login' %}">Bxід</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="row">
      <nav class = "col-md-auto nav flex-column border">
        <a class= "nav-link root" href= "{% url 'main:index' %}">Головна</a>
        <span class= "nav-link root font-weight-bold">Нерухомість </span>
          <a class="nav-link" hrеf= "#">Житло</a>
          <a class="nav-link" hrеf="#">Склади</a>
          <a class= "nav-link" hrеf= "#">Гаражі</a>
        <span class= "nav-link root font-weight-bold" href= "#" >Транспорт</span>
          <a class="nav-link" hrеf= "#">Легковий</a>
          <a class="nav-link" hrеf= "#">Вантажний</a>
        <a class= "nav-link root" href="{% url 'main:other' page='about' %}">Про сайт</a>
      </nav>
      <section class = "col border pу-2">
          {% bootstrap_messages %}
          {% block content %}
          {% endblock %}
      </section>
    </div>
      <footer class="mt-3" >
        <p class=" text-right font-italic" >&copy; читачі.</p>
      </footer>
  </body>
</html>

main/templates/main/about.html
{% extends "layout/basic.html" %}
{% block title %}Про сайт{% endblock %}
{% block content %}
<h2>Про сайт</h2>
<p>Сайт для публікації оголошень про продаж, розбитих на рубрики</p>
<p>Всі права належать читачам книги &laquo;Django 3.0&raquo;.</p>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<<h2>Останні 10 оголошень</h2>
{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}
{% load boostrap4 %}
{% block title %} Вхід {% endblock %}

{% block content %}
<h2>Вхід</h2>
{% if user.id_authenticated %}
<p>Ви вже виконали вхід</p>
{% else %}
<form method="post">
  {% csrf_token %}
  {% boostrap_form form layout='horizontal' %}
  <input type="hidden" name="text" value="{{ next }}">
  {% buttons submit="Віійти" %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Вихід {% endblock %}

{% block content %}
<h2 >Вихід</h2>
<р>Ви успішно вийшли з сайту. </р>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %}Профіль користувача{% endblock %}

{% block content %}
<h2>Профіль користувача</h2>
{% if user.first_name and user.last_name %}
<p>Привіт, {{% user.first_name %} {{% user.last_name %}}!</p>
{% else %}
<p>Привіт!</p>
{% endif %}
<h3>Ваші оголошення</h3>
{% endblock %}